### ISSUE TITLE
Ability to replace container after initialization

### ISSUE THREAD

**Issue by Kukunin** [dry-rb/dry-auto_inject#37]
`include Import` construction requires `dry-auto_inject` injector to be present on load time.

But dependency might be set after application is loaded, and before it start the work.

Good example, when I use `include Import` in a gem, and then, I load gem first, and define container after my main application is loaded.

Currently it's impossible, because `include Import` injects container to every class on load time, not while new instance is creating.

Also, In integration tests it'd be cool to replace container.

Overall, it'd be better to have lazy load for dependencies from a container.

**Comment by solnic** [comment]
This stuff is designed to work in applications, not gems, so I'd like to know a bit more about your use case first. In general the whole point of this setup is to NOT mutate container at run-time, that's why we freeze it. In tests you can skip finalization and can use `stub` API to replace certain deps with stubs, that's really all you need from testing pov (and we're about to introduce a test mode for dry system so that freezing will be skipped when it's turned on).

**Comment by apohllo** [comment]
Hmm, well I am wondering how I should do that in practice (in regular context, i.e. an application). The `include Import` statement requires that the `Import` is already defined (at the moment the classes are loaded). I have no idea how to skip finalization. The example says:
```
Import = Dry::AutoInject(MyContainer)
```
I guess it is finalizing the container definition. I know I can override the arguments of the classes in the constructor, i.e.

```
class MyContainer
  register :some_repo, -> { RealRepo.new }
end

class SomeClass
  include Import["some_repo"]
end

SomeClass.new(some_repo: FakeRepo.new)
```

But how to stub the repo using the `stub` API? I tired that and it seems, the the stubbed version is not visible to `SomeClass` since it uses the `RealRepo`, even though I make a following call:

```
MyContainer.stub(:some_repo, FakeRepo.new)
```
Shall I assume that the only way to use the stubbed version of the dep. is via the constructor?

**Comment by flash-gordon** [comment]
I'm going to close this issue since it's more a discussion rather than a bug or a feature request. If you're interested in this issue please use our chat or start a new discussion referencing this issue at https://discourse.dry-rb.org/
